root_instance_type = "t2.micro"
root_pem_key = "terra_key"
root_bucket_name = "my-s3-backend-949875"
root_sse_algorithm_type = "AES256"
root_dynamobd_name = "dynamodb_state_locking_table"
root_hash_key = "LockID"